- name: Configure Postal user.
  user:
    name: postal
    shell: /bin/bash
    comment: "Postal user"
    home: /opt/postal
    state: present
    system: yes

- name: Create the Postal directory
  file:
    path: /opt/postal/app/
    owner: postal
    state: directory

- name: Git clone of postal install
  ansible.builtin.git:
    repo: https://postalserver.io/start/install 
    dest: /opt/postal/install

# - name: Download latest release of Postal.
#   unarchive:
#     src: https://postal.atech.media/packages/stable/latest.tgz
#     dest: /opt/postal/app/
#     remote_src: yes
#     owner: postal

- name: Create symbolic link to Postal binary.
  file:
    src: /opt/postal/install/bin/postal
    dest: /usr/bin/postal
    state: link

# - name: Install required dependencies via bundler.
#   command: postal bundle /opt/postal/vendor/bundle

- name: Bootstrap postal 
  command: postal bootstrap {{ postal_web_host }}

- name: Save the secret key to the Postal home directory.
  shell: >
    cat /opt/postal/config/postal.yml |
    yq .rails.secret_key |
    sed -e 's/^"//' -e 's/"$//' >
    "{{ postal_secret_key_file }}"

- name: Make sure the secret key is secure.
  file:
    path: "{{ postal_secret_key_file }}"
    owner: postal
    group: root
    mode: 0600

- name: Pull images for postal
  command: docker compose -f /opt/postal/install/docker-compose.yml -p postal  pull

# - name: Initialize the postal config.
#   command: postal initialize
