# - name: Start service mariadb, if not started
#   ansible.builtin.service:
#     name: mariadb
#     state: started

- name: Ensure root password for all root accounts
  mysql_user:
    name: "{{ mysql_root_username }}"
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ inventory_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: Copy mysql-client authentication file and secure it
  template:
    src: root/my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False

- name: Remove anonymous users
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User=''
  changed_when: False

- name: Remove test database and access to it
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - DROP DATABASE IF EXISTS test
    - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%'
  changed_when: False

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}"'
  with_items:
    - FLUSH PRIVILEGES
  changed_when: False